apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-tls
spec:
  commonName: kafka
  dnsNames:
  - kafka-0.kafka-headless.default.svc.cluster.local
  - kafka-headless.default.svc.cluster.local
  - kafka.default.svc.cluster.local
  duration: 24h
  secretName: kafka-tls
  additionalOutputFormats:
  - type: CombinedPEM
  - type: DER
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ruby-client
spec:
  commonName: ruby-client
  duration: 1h
  secretName: ruby-client
  additionalOutputFormats:
  - type: CombinedPEM
  - type: DER
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io