apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ruby
  name: ruby
  namespace: default
spec:
  initContainers:
  containers:
  - command: ['/bin/sh', "-c"]
    args:
    - git clone https://github.com/franktylerva/kafka-ruby.git code;
      cd code;
      bundle install --gemfile=/code/Gemfile;
      sleep infinity;
    image: ruby
    name: ruby
    env:
    - name: TLS_KEY
      valueFrom:
        secretKeyRef:
          name: ruby-client
          key: tls.key
    - name: TLS_CRT
      valueFrom:
        secretKeyRef:
          name: ruby-client
          key: tls.crt
    - name: CA_CRT
      valueFrom:
        secretKeyRef:
          name: ruby-client
          key: ca.crt
    volumeMounts:
    - name: tls-volume
      readOnly: true
      mountPath: "/tmp/tls"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: tls-volume
    secret:
      secretName: ruby-client